// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	usecase "image-processor/usecase"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUsecase is a mock of IUsecase interface.
type MockIUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIUsecaseMockRecorder
}

// MockIUsecaseMockRecorder is the mock recorder for MockIUsecase.
type MockIUsecaseMockRecorder struct {
	mock *MockIUsecase
}

// NewMockIUsecase creates a new mock instance.
func NewMockIUsecase(ctrl *gomock.Controller) *MockIUsecase {
	mock := &MockIUsecase{ctrl: ctrl}
	mock.recorder = &MockIUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsecase) EXPECT() *MockIUsecaseMockRecorder {
	return m.recorder
}

// Compress mocks base method.
func (m *MockIUsecase) Compress(arg0 context.Context, arg1 *multipart.FileHeader, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compress", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compress indicates an expected call of Compress.
func (mr *MockIUsecaseMockRecorder) Compress(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compress", reflect.TypeOf((*MockIUsecase)(nil).Compress), arg0, arg1, arg2)
}

// Convert mocks base method.
func (m *MockIUsecase) Convert(arg0 context.Context, arg1 *multipart.FileHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Convert indicates an expected call of Convert.
func (mr *MockIUsecaseMockRecorder) Convert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockIUsecase)(nil).Convert), arg0, arg1)
}

// Resize mocks base method.
func (m *MockIUsecase) Resize(arg0 context.Context, arg1 *multipart.FileHeader, arg2 *usecase.ResizeOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resize indicates an expected call of Resize.
func (mr *MockIUsecaseMockRecorder) Resize(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockIUsecase)(nil).Resize), arg0, arg1, arg2)
}
